apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: auth-postgres-connection
spec:
  type: kv-v2
  mount: kvv2
  path: main/auth/postgres-connection
  refreshAfter: 30s
  vaultAuthRef: static-auth
  destination:
    name: auth-postgres-connection
    create: true

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: auth-redis-connection
spec:
  type: kv-v2
  mount: kvv2
  path: main/auth/redis-connection
  refreshAfter: 30s
  vaultAuthRef: static-auth
  destination:
    name: auth-redis-connection
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: auth-s3-access
spec:
  type: kv-v2
  mount: kvv2
  path: main/auth/s3-access
  refreshAfter: 30s
  vaultAuthRef: static-auth
  destination:
    name: auth-s3-access
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: auth-service-account-credentials
spec:
  type: kv-v2
  mount: kvv2
  path: main/auth/service-account-credentials
  refreshAfter: 30s
  vaultAuthRef: static-auth
  destination:
    name: auth-service-account-credentials
    create: true
