
services:

  backend:
    image: auth-backend
    container_name: auth-backend
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    volumes:
      - .:/usr/src/app
    env_file:
      - ./docker/development/.env

  redis:
    container_name: auth-redis
    image: redis:latest

  postgres:
    container_name: auth-postgres
    image: postgres:14-alpine
    env_file:
      - ./docker/development/.env
