apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: auth-postgres-connection
spec:
  path: dev/auth/postgres-connection
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: auth-redis-connection
spec:
  path: dev/auth/redis-connection
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: auth-s3-access
spec:
  path: dev/auth/s3-access
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: auth-service-account-credentials
spec:
  path: dev/auth/service-account-credentials
